# Generated by Django 3.1.2 on 2020-10-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profiletwo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileTwo',
        ),
    ]
