# Generated by Django 3.1.2 on 2020-11-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_profiletwo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileTwo',
        ),
    ]
