# Generated by Django 3.1.2 on 2020-11-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnosmodel',
            name='email',
            field=models.CharField(max_length=80),
        ),
    ]
